name = "flashcard"
main = "functions/index.ts"
compatibility_date = "2025-01-01"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = ["/api/*"]

[[d1_databases]]
binding = "DB"
database_name = "flashcard-db"
database_id = "7be4ac2d-e06c-4aed-ac66-634b8d447ada"
